unit fConst;

interface


type
  //setofbyte = set of byte;
  TArrInt   = array of Integer;
  DataRec = record
    ID : Integer;
    ParamStr : array[0..99] of string[255];
    ParamInt : array[0..99] of Integer;
    ParamBoo : array[0..99] of Boolean;
    ParamDate: array[0..99] of TDateTime;
    ParamStatus: array[0..99] of String;
  end;

const
	HARI_ID:array[1..7] of string = ('Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jum''at', 'Sabtu');

  DBTPK_REF_TABLE : array [0..21] of string =(
      'OPS_PESERTA_DB', 'OPS_PESERTA_KR', 'OPS_WILAYAH_KLIRING',
			'REF_ALASAN_PENOLAKAN', 'REF_JENIS_BANK', 'REF_JENIS_KEPESERTAAN',
      'REF_JENIS_NASABAH', 'REF_JENIS_SARANA_TRANSAKSI',
			'REF_JENIS_TRANSAKSI', 'REF_JENIS_USAHA', 'REF_KOTA', 'REF_PESERTA',
      'REF_PESERTA_KONVERSI', 'REF_PESERTA_WILAYAH', 'REF_STATUS_PENDUDUK',
      'REF_WILAYAH_KLIRING', 'REF_WILAYAH_KOTA', 'REF_PROPINSI',
      'OPS_ZONA_DB_INDV', 'REF_KODE_ERROR', 'REF_HARI_LIBUR_WILAYAH', 'REF_HARI_LIBUR_NASIONAL');

	FIELD_OPS_PESERTA_DB								= 'TANGGAL,BIC_PESERTA,AKTIF_KLIRING_INDV,AKTIF_KLIRING_BULK,PREFUND_CASH_AWAL,PREFUND_CASH_TOPUP,' +
                                        'PREFUND_KOLATERAL,TOTAL_PREFUND_DB,TOTAL_PENYERAHAN_OUTWARD,TOTAL_PENGEMBALIAN_OUTWARD,'+
                                        'TOTAL_PENGEMBALIAN_H1_OUTWARD,TOTAL_PENYERAHAN_INWARD,TOTAL_PENGEMBALIAN_INWARD,TOTAL_PENGEMBALIAN_H1_INWARD,'+
                                        'TOTAL_TRANSAKSI,NET_BSK_DB,MINIMUM_PREFUND_DB,RELEASE_PREFUND_DB,RELEASE_PREFUND_KOLATERAL,PENGEMBALIAN_PREFUND_DB,'+
                                        'PEMAKAIAN_PREFUND_DB,PELIMPAHAN_PREFUND';

 	FIELD_OPS_PESERTA_KR								= 'TANGGAL,BIC_PESERTA,AKTIF_KLIRING_INDV,AKTIF_KLIRING_BULK,PREFUND_CASH_AWAL,PREFUND_CASH_TOPUP'+
                                        ',PREFUND_KOLATERAL,TOTAL_TRANSAKSI,TOTAL_KR_INWARD,TOTAL_KR_OUTWARD,RELEASE_PREFUND_KR,RELEASE_PREFUND_KOLATERAL'+
                                        ',PENGEMBALIAN_PREFUND_KR,PEMAKAIAN_PREFUND_KR,NET_BSK_KR,PELIMPAHAN_PREFUND';

  FIELD_OPS_WILAYAH_KLIRING						= 'TANGGAL,SANDI_WILAYAH_KLIRING,SANDI_ZONA,DELETED,STATUS_WILAYAH';
  FIELD_REF_ALASAN_PENOLAKAN					= 'SANDI,ALASAN,DELETED,UPDATE_SEQ,PEMBEBANAN,BIAYA_SANKSI';
  FIELD_REF_JENIS_BANK								= 'SANDI_JENIS_BANK,JENIS_BANK,DELETED,UPDATE_SEQ';
  FIELD_REF_JENIS_KEPESERTAAN					= 'SANDI_JENIS_KEPESERTAAN,JENIS_KEPESERTAAN,DELETED,UPDATE_SEQ';
  FIELD_REF_JENIS_NASABAH							= 'SANDI_JENIS_NASABAH,JENIS_NASABAH,DELETED,UPDATE_SEQ';
  FIELD_REF_JENIS_SARANA_TRANSAKSI		= 'SANDI_JENIS_SARANA_TRANSAKSI,JENIS_SARANA_TRANSAKSI,DELETED,UPDATE_SEQ';
  FIELD_REF_JENIS_TRANSAKSI						= 'SANDI_TRANSAKSI,JENIS_TRANSAKSI,INSTITUSI,SANDI_GRUP_TRANSAKSI,CAPPING'+
                                        ',BIAYA_DKE,PAJAK_DKE,BIAYA_BULK,PAJAK_BULK,DELETED,UPDATE_SEQ,SANDI_JENIS_LAYANAN';
  FIELD_REF_JENIS_USAHA								= 'SANDI_JENIS_USAHA,JENIS_USAHA,DELETED,UPDATE_SEQ';
  FIELD_REF_KOTA											= 'SANDI_KOTA,NAMA_KOTA,SANDI_PROPINSI,DELETED,UPDATE_SEQ';
  FIELD_REF_PESERTA										= 'BIC_PESERTA,NAMA_PESERTA,NAMA_SINGKAT,SANDI_INSTITUSI_PESERTA'+
                                        ',SANDI_KLIRING_KANTOR_PUSAT,NAMA_KANTOR_PUSAT,SANDI_KOTA,KODE_POS,NO_TELP'+
                                        ',NO_FAX,ALAMAT,SANDI_KEPESERTAAN,SANDI_JENIS_USAHA,SANDI_JENIS_BANK'+
                                        ',NO_REK_SETELMEN,BIC_PESERTA_SETELMEN,TANGGAL_EXP_CERTIFICATE,CERTIFICATE'+
                                        ',PUBLIC_KEY,STATUS_PESERTA,DELETED,UPDATE_SEQ,NO_REK,LANGGANAN_AGREGAT';
  FIELD_REF_PESERTA_KONVERSI					= 'BIC_PESERTA_ASAL,BIC_PESERTA_KONVERSI,TANGGAL_AKTIF,TANGGAL_TUTUP,DELETED,UPDATE_SEQ';
  FIELD_REF_PESERTA_WILAYAH						= 'BIC_PESERTA,SANDI_WILAYAH_KLIRING,TGL_AKTIF,DELETED,UPDATE_SEQ';
  FIELD_REF_STATUS_PENDUDUK						= 'SANDI_STATUS_PENDUDUK,STATUS_PENDUDUK,DELETED,UPDATE_SEQ';
  FIELD_REF_WILAYAH_KLIRING						= 'SANDI_WILAYAH_KLIRING,SANDI_ZONA,NAMA_WILAYAH_KLIRING,TIPE_KOORDINATOR,SANDI_KOORDINATOR,NAMA_KOORDINATOR,NO_TELP_KOORDINATOR'+
                                        ',CP_KOORDINATOR,ALAMAT_KOORDINATOR,SANDI_SATKER,OTOMASI,DELETED,UPDATE_SEQ';
  FIELD_REF_WILAYAH_KOTA							= 'SANDI_WILAYAH_KLIRING,SANDI_KOTA,TGL_AKTIF,DELETED,UPDATE_SEQ';
  FIELD_REF_PROPINSI									= 'SANDI_PROPINSI,NAMA_PROPINSI,DELETED,UPDATE_SEQ';
  (*
  FIELD_OPS_ZONA_DB_INDV							= 'TANGGAL,SANDI_ZONA,START_WT_PENYERAHAN,START_WT_PENYERAHAN_OLD'+
                                        ',COT_WT_PENYERAHAN,COT_WT_PENYERAHAN_OLD,START_WT_PENGEMBALIAN,START_WT_PENGEMBALIAN_OLD'+
                                        ',COT_WT_PENGEMBALIAN,COT_WT_PENGEMBALIAN_OLD,COT_FTS_ZONA,COT_FTS_ZONA_OLD,POLA_SIKLUS_KLIRING,SANDI_BUKU'+
                                        ',STATUS_WT_PENYERAHAN,STATUS_WT_PENGEMBALIAN,AUTO_OPEN_WT_PENYERAHAN,AUTO_CLOSE_WT_PENYERAHAN'+
                                        ',AUTO_OPEN_WT_PENGEMBALIAN,AUTO_CLOSE_WT_PENGEMBALIAN,STATUS,IS_END_ZONA,IS_END_ZONA_OLD,STATUS_BSK';
  *)
  FIELD_OPS_ZONA_DB_INDV							= 'TANGGAL,SANDI_ZONA,AUTO_OPEN_WT_PENYERAHAN,AUTO_CLOSE_WT_PENYERAHAN,POLA_SIKLUS_KLIRING'+
                                        ',AUTO_OPEN_WT_PENGEMBALIAN,AUTO_CLOSE_WT_PENGEMBALIAN,STATUS,IS_END_ZONA,IS_END_ZONA_OLD,STATUS_BSK';
  FIELD_REF_KODE_ERROR								= 'KODE_ERROR,DESKRIPSI,DELETED,UPDATE_SEQ';
  FIELD_REF_HARI_LIBUR_WILAYAH 				= 'SANDI_WILAYAH_KLIRING,TANGGAL,KETERANGAN,DELETED,UPDATE_SEQ';
  FIELD_REF_HARI_LIBUR_NASIONAL 			= 'TANGGAL,KETERANGAN,DELETED,UPDATE_SEQ';


  DBTPK_FIELD_REF_TABLE : array [0..21] of string = (
      FIELD_OPS_PESERTA_DB, FIELD_OPS_PESERTA_KR, FIELD_OPS_WILAYAH_KLIRING,
			FIELD_REF_ALASAN_PENOLAKAN, FIELD_REF_JENIS_BANK, FIELD_REF_JENIS_KEPESERTAAN,
      FIELD_REF_JENIS_NASABAH, FIELD_REF_JENIS_SARANA_TRANSAKSI, FIELD_REF_JENIS_TRANSAKSI,
      FIELD_REF_JENIS_USAHA, FIELD_REF_KOTA, FIELD_REF_PESERTA, FIELD_REF_PESERTA_KONVERSI,
      FIELD_REF_PESERTA_WILAYAH, FIELD_REF_STATUS_PENDUDUK, FIELD_REF_WILAYAH_KLIRING,
      FIELD_REF_WILAYAH_KOTA,FIELD_REF_PROPINSI,FIELD_OPS_ZONA_DB_INDV, FIELD_REF_KODE_ERROR,
      FIELD_REF_HARI_LIBUR_WILAYAH, FIELD_REF_HARI_LIBUR_NASIONAL);


  { Parameters }  { DB: APOKUSER ;  TABLE: params  ;  FIELD: para_id }
  PARA_MIN_PASS_LENGTH     = 1;//21;
  PARA_MAX_PASS_LENGTH     = 2;//22;
  PARA_MIN_USER_LENGTH     = 3;//23;
  PARA_MAX_USER_LENGTH     = 4;//24;
  PARA_PASSWORD_EXPIRE     = 5;//25;
  PARA_PASSWORD_HISTORY    = 6;//26;
  PARA_USE_MAX_LOGON			 = 7;

  { Parameters }  { DB: APOKDB ;  TABLE: ref_param  ;  FIELD: para_id }
  PARA_PRESENT_WORK_DATE   =  1;
  PARA_PREV_WORK_DATE      =  2;
  PARA_NEXT_WORK_DATE      =  3;
  PARA_PROCESS_STATUS      =  4;
  PARA_SYS_STATUS          =  5;
  PARA_ACT_WIL_KLIRING     =  6;
  PARA_COMMAND_TIME_OUT    =  7;
  PARA_DB_LOCATION         =  8;
  PARA_CONTINUE_SOD        =  9;
  PARA_CONTINUE_EOD        =  10;
  PARA_POCKET_COUNT				 =  11;
  PARA_INPUT_FILE_TYPE		 =  12;
  PARA_STARTING_POCKET     =  13;

  PARA_PROCESS_FEE         = 31;
  PARA_POCKET_FEE          = 32;
  PARA_REJECT_FEE          = 33;

  PARA_TEMP_ACC_NO         = 41;
  PARA_FEE_INCOME_ACC_NO   = 42;
  PARA_BENEFICIARY_ACC_NO  = 43;
  PARA_FEE_INCOME_REJ_ACC_NO   = 44;

  PARA_POST_UNIT_CODE      = 51;
  PARA_CLEARING_POST_CODE  = 52;
  PARA_CLEARING_TRN_CODE   = 53;
  PARA_FEE_POST_CODE       = 54;
  PARA_FEE_TRN_CODE1       = 55;
  PARA_FEE_TRN_CODE2       = 56;
  PARA_FEE_OSA_POST_CODE   = 57;
  PARA_FEE_CONSTANT        = 58;

  PARA_FTP_ADD1            = 81;
  PARA_FTP_USR1            = 82;
  PARA_FTP_PASS1           = 83;
  PARA_FTP_ADD2            = 84;
  PARA_FTP_USR2            = 85;
  PARA_FTP_PASS2           = 86;
  PARA_FTP_ADD3            = 87;
  PARA_FTP_USR3            = 88;
  PARA_FTP_PASS3           = 89;

  PARA_WIN_SHARED_FOLDER1  = 91;
  PARA_WIN_SHARED_FOLDER2  = 92;
  PARA_WIN_SHARED_FOLDER3  = 93;
  PARA_WIN_SHARED_FOLDER4  = 94;
  PARA_WIN_SHARED_FOLDER5  = 95;
  PARA_WIN_SHARED_FOLDER6  = 96;
  PARA_WIN_SHARED_FOLDER7  = 97;
  PARA_WIN_SHARED_FOLDER8  = 98;
  PARA_WIN_SHARED_FOLDER9  = 99;

  PARA_LOAD_DATA_DONE      = 101;
  PARA_BACKUP_USER_DONE    = 102;
  PARA_BACKUP_MAIN_DONE    = 103;
  PARA_BACKUP_TRX_DONE     = 104;
  PARA_REKAP_DATA_DONE   	 = 122;

  PARA_FI_IMP_TBL_DIMENSI_DONE = 105;
  PARA_FI_EKS_CLSEMUA_DONE     = 106;
  PARA_FI_EKS_TRX_BSK_DONE     = 107;
  PARA_FI_EKS_FEE_PROCESS_DONE = 108;
  PARA_FI_EKS_FEE_RJT_DONE     = 109;
  PARA_FI_EKS_SORT_PATTERN_DONE= 110;
  PARA_FI_EKS_SANDI_BANK_DONE  = 121;

  PARA_REPORT_1_DONE       = 111;
  PARA_REPORT_2_DONE       = 112;
  PARA_REPORT_3_DONE       = 113;
  PARA_REPORT_4_DONE       = 114;
  PARA_REPORT_5_DONE       = 115;
  PARA_REPORT_6_DONE       = 116;
  PARA_REPORT_7_DONE       = 117;
  PARA_REPORT_8_DONE       = 118;
  PARA_REPORT_9_DONE       = 119;
  PARA_REPORT_10_DONE      = 120;

  PARA_SKN_SOD             = 1000;
  PARA_SKN_EOD             = 1100;
  PARA_RPT_LEFT_TITLE_1		 = 1001;
  PARA_RPT_LEFT_TITLE_2		 = 1002;

  PARA_FILE_CLSEMUA        = 601;
  PARA_FILE_BSK            = 602;
  PARA_FILE_BIAYA1         = 603;
  PARA_FILE_BIAYA2         = 606;
  PARA_FILE_BKBR           = 605;
  PARA_FOLDER_SP           = 604;
  PARA_FILE_ICRE           = 98;

  { Module / Menu Access }
  MDL_Login                =  0;  // Login
  MDL_SE                   =  1;  // SOD EOD
  MDL_TRX                  =  2;  // Transaksi
  MDL_RPT                  =  3;  // Laporan
  MDL_FI                   =  4;  // File Interface
  MDL_PS                   =  5;  // Parameter Sistem
  MDL_UMC                  =  6;  // User Management Console
  MDL_MDB                  =  7;  // Maintenance DB
  MDL_OUT_CREDIT_INTERFACE =  8;  // Interface Out Credit
  MDL_INTERFACE_SPK        =  9;  // Interface SPK
  MDL_EXPORT_DKI					 =  10;
  MDL_IMPORT_DKI 					 =  11;
  MDL_DISTR_DKI 					 =  12;
  MDL_VERIFIKASI_DKI			 =  13;
  MDL_INTF_RETUR					 =  14;
  MDL_EXPORT_DPI					 =  15;

  MDL_Login_TEXT					 =  'Login';
  MDL_SE_TEXT              =  'SOD/EOD';
  MDL_TRX_TEXT             =  'Transaksi';
  MDL_RPT_TEXT             =  'Laporan';
  MDL_FI_TEXT              =  'File Interface';
  MDL_PS_TEXT              =  'Parameter Sistem';
  MDL_UMC_TEXT             =  'User Management Console';
  MDL_MDB_TEXT             =  'Maintenance DB';
  MDL_OUT_CREDIT_INTERFACE_TEXT  =  'Interface Kredit Penyerahan';
  MDL_INTERFACE_SPK_TEXT   =  'Interface DKI-SPK';
  MDL_EXPORT_DKI_TEXT			 =  'Interface Export DKI';
  MDL_IMPORT_DKI_TEXT		   =  'Interface Import DKI';
  MDL_DISTR_DKI_TEXT 			 =  'Distribusi Verifikasi Kredit Masuk';
  MDL_INTF_RETUR_TEXT			 =  'Interface Retur Keluar';

  { ACCESS RIGHTS }
  UMC_NEWUSER              =  500;
  UMC_MANAGEUSER           =  501;
  UMC_VALIDATEUSER         =  502;
  UMC_UNLOCKUSER           =  503;
  UMC_REMOVEUSER           =  504;
  UMC_NEWGROUP             =  505;
  UMC_MANAGEGROUP          =  506;
  UMC_VALIDATEGROUP        =  507;
  UMC_REMOVEGROUP          =  508;
  UMC_OPTIONS              =  509;
  UMC_RESET_PASSWORD       =  510;


  ACT_NEW                =  1;
  ACT_EDIT               =  2;
  ACT_DELETE             =  3;
  ACT_VALIDATE           =  4;
  ACT_ENABLE             =  5;
  ACT_DISABLE            =  6;
  ACT_UNLOCK             =  7;
  ACT_CHG_PASS           =  8;
  ACT_CHG_ADD_GRP        =  9;
  ACT_CHG_RMV_GRP        = 10;
  ACT_CHG_ACCESS_SET     = 11;
  ACT_CHG_ACCESS_UNSET   = 12;
  ACT_OPTIONS            = 13;
  ACT_REPORT             = 14;
  ACT_LOGIN              = 15;
  ACT_LOGOFF             = 16;
  ACT_AUTO_LOGOFF        = 17;

  ACT_SET_MASTER_KEY     = 18;
  ACT_CONFIRM_MASTER_KEY = 19;

  ACT_SEARCH             = 20;
  ACT_PRINT              = 21;

  ACT_EXECUTE            = 22;

  //DLL Call Function
  LIB_SOD = 1;
  LIB_USER_MGR = 2;
  LIB_PARAM_SISTEM = 3;
  LIB_PARAM_WILAYAH = 4;
  LIB_PARAM_CABANG = 5;
  LIB_PARAM_CAPEM = 6;
  LIB_TABEL_DIMENSI = 7;
  LIB_BACKUP_DB = 8;
  LIB_RESTORE_DB = 9;
  LIB_DOWNLOAD_BIMC = 10;
  LIB_REJECT_REPAIR_DEBET = 11;
  LIB_REJECT_REPAIR_CREDIT = 12;
  LIB_AUTHORIZE_TRX_DEBET = 13;
  LIB_AUTHORIZE_TRX_CREDIT = 14;
  LIB_MONITORING_TRX = 15;
  LIB_GENERATE_DPO = 16;
  LIB_CARI_WARKAT = 17;
  LIB_REPORT_DETAIL = 18;
  LIB_MANAGE_TRX = 19;
	LIB_INTERFACE_SPK = 20;
  LIB_PARAM_DOWNLOAD_DATA_HOST = 21;
  LIB_DB_LAPORAN_DETAIL = 22;
  LIB_DB_LAPORAN_DELETED = 23;
  LIB_KR_LAPORAN_DETAIL = 24;
  LIB_KR_LAPORAN_DELETED = 25;
  LIB_LAPORAN_SUMMARY = 26;
  LIB_PARAM_IMPORT_DKI = 27;
  LIB_IMPORT_DKI = 28;
	LIB_RESEND_SPK = 29;
  LIB_PARAM_KODE_POSTING = 30;
	LIB_IMPORT_DKIHOST = 31;
  LIB_DISTRIBUSI_KREDIT_MASUK = 32;
  LIB_PARAM_USER_VERIFY = 33;
  LIB_VERIFIKASI_KREDIT_MASUK = 34;
  LIB_OTORISASI_KREDIT_MASUK = 35;
  LIB_REPORT_STATUS_BATCH = 36;
  LIB_UPLOAD_DKI = 37;
  LIB_CARI_WARKAT_INCR = 38;
  LIB_REPORT_INCR_DETAIL = 39;
  LIB_REPORT_INCR_PER_KODE_POSTING = 40;
  LIB_REPORT_INCR_REKAP = 41;
  LIB_INTF_RETUR_KREDIT_KELUAR = 46;
  LIB_EXPORT_DPI = 42;
  LIB_PARAM_EXPORT_DPISPK = 43;
  LIB_INDB_LAPORAN_DETAIL = 44;
  LIB_INDB_LAPORAN_SUMMARY = 45;

  LIB_TOOLS_PARAM_CONVERT_RTGS2SKN = 410;
  LIB_TOOLS_CONVERT_RTGS2G2INDV = 901;
  LIB_TOOLS_CONVERT_RTGS2SWIFT = 902;
  LIB_TOOLS_CARI_KONVERSI = 903;
  LIB_REPORT_CONVERT_PER_FILE = 904;
  LIB_REPORT_CONVERT_DKOI = 905;
  LIB_REPORT_CONVERT_REMM = 906;
  LIB_REPORT_CONVERT_SWIFT = 907;


  DLL_CALL_SOD = 'libSetting;CallSOD';
  DLL_CALL_DOWNLOAD_BIMC = 'libDLBIMC;CallDownloadBIMC';
  DLL_CALL_REJECT_REPAIR = 'libRR;CallRejectRepairDebet';
  DLL_CALL_AUTH_REPAIR_DEBET = 'libRR;CallAuthRepairDebet';
  DLL_CALL_REJECT_REPAIR_CREDIT = 'libRR;CallRejectRepairCredit';
  DLL_CALL_AUTH_REPAIR_CREDIT = 'libRR;CallAuthRepairCredit';
  DLL_CALL_GENERATE_DPO = 'libGenDKE;GenDKE';
  DLL_CALL_MONITORING_TRX = 'libMonTrx;CallMonTrx';
  DLL_CALL_MANAGE_TRX = 'libManageTrx;CallManageTrx';
  DLL_CALL_REPORT_DETAIL = '';//'libReport;CallReport';
  DLL_CALL_CARI_WARKAT = 'libFind;CallFind';
  DLL_CALL_PARAM_SYS = 'libSetting;CallSysParam';
  DLL_CALL_PARAM_WILAYAH = 'libSetting;CallRegionParam';
  DLL_CALL_PARAM_CABANG = 'libSetting;CallBranchParam';
  DLL_CALL_PARAM_CAPEM = 'libSetting;CallSubBranchParam';
  DLL_CALL_PARAM_DBTPK = 'libSetting;CallImportDBTPK';
  DLL_CALL_BACKUP_DB = 'libBRDB;CallBackupDB';
  DLL_CALL_RESTORE_DB = 'libBRDB;CallRestoreDB';
  DLL_CALL_INTERFACE_SPK = 'libSPK;CallIntfSPK';
  DLL_CALL_PARAM_DOWNLOAD_DATA_HOST = 'libDLBIMC;CallConfigDH';
  DLL_CALL_DB_LAPORAN_DETAIL ='libReport;CallDBReportDetail';
  DLL_CALL_DB_LAPORAN_DELETED = 'libReport;CallDBReportDeleted';
  DLL_CALL_KR_LAPORAN_DETAIL = 'libReport;CallKRReportDetail';
  DLL_CALL_KR_LAPORAN_DELETED = 'libReport;CallKRReportDeleted';
  DLL_CALL_LAPORAN_SUMMARY = 'libReport;CallReportSummary';
  DLL_CALL_PARAM_IMPORT_DKI = 'libImportDKI;CallParamImportDKI';
  DLL_CALL_IMPORT_DKI = 'libImportDKI;CallImportDKI';
  DLL_CALL_RESEND_SPK = 'libReSend;CallResendToSPK';
	DLL_CALL_PARAM_KODE_POSTING = 'libPC;CallParamKodePosting';
  DLL_CALL_IMPORT_DKIHOST = 'libCROUT;CallImportDKIHost';
  DLL_CALL_DISTRIBUSI_KREDIT_MASUK = 'libDist;CallDistTrx';
  DLL_CALL_PARAM_USER_VERIFY = 'libDist;CallParamUserVerify';
  DLL_CAL_VERIFIKASI_KREDIT_MASUK = 'libVerify;CallDKEVerification';
  DLL_CAL_OTORISASI_KREDIT_MASUK  = 'libVerify;CallDKEAuthorization';
  DLL_CALL_REPORT_STATUS_BATCH = 'libBatchStat;CallBatchStatus';
  DLL_CALL_UPLOAD_DKI = 'libCRCTX;CallUploadDKI';
  DLL_CALL_CARI_WARKAT_INCR = 'libINCRFind;CallFind';
  DLL_CALL_REPORT_INCR_DETAIL = 'libINCRPT;CallRptDetail';
  DLL_CALL_REPORT_INCR_PER_KODE_POSTING = 'libINCRPT;CallRptDetailByPostingCode';
  DLL_CALL_REPORT_INCR_REKAP = 'libINCRPT;CallRptSummary';
  DLL_CALL_INTF_RETUR_KREDIT_KELUAR = 'libINRET;CallOutRetur';
  DLL_CALL_EXPORT_DPI = 'libImportDPI;CallExportDPI';
  DLL_CALL_PARAM_EXPORT_DPISPK = 'libImportDPI;CallParamExportDPI';
  DLL_CALL_INDB_LAPORAN_DETAIL ='libINDBReport;CallDBReportDetail';
  DLL_CALL_INDB_LAPORAN_SUMMARY ='libINDBReport;CallReportSummary';
  DLL_CALL_TOOLS_CONVERT_RTGS2G2INDV='libRTGS2G2;CallConvRTGS2G2';
  DLL_CALL_TOOLS_PARAM_CONVERT_RTGS2SKN='libRTGS2G2;CallConvParam';
  DLL_CALL_REPORT_CONVERT_PER_FILE = 'libRTGS2G2;CallRptPerProsesFile';
  DLL_CALL_REPORT_CONVERT_DKOI = 'libRTGS2G2;CallRptKonversiSKN';
  DLL_CALL_REPORT_CONVERT_REMM = 'libRTGS2G2;CallRptKonversiREMM';
  DLL_CALL_REPORT_CONVERT_SWIFT = 'libRTGS2G2;CallConvParam';
  DLL_CALL_TOOLS_CARI_KONVERSI = 'libRTGS2G2;CallCariData';

  ID_SHARE_MEMORY_SEND_DKE_INDV   = 'smDKEI';
  ID_SHARE_MEMORY_GET_DKE_INDV  	= 'smDKEI2';
  PARAM_TRX_DATE			 				    = 12;
  PARAM_SPK_WSDL_ADDRESS          = 22;
  PARAM_SPK_AUTH_CODE             = 23;
  PARAM_STR_BIC_PESERTA_ACTIVE    = 24;
  PARAM_SPK_DKE_PERIODE_INDV      = 25;
  PARAM_SPK_DKE_KOTA_INDV         = 26;
  PARAM_SPK_DKE_ZONA_INDV         = 27;

  PARAM_SPK_DKE_FILE_INDV         = 37;
  PARAM_SPK_DKE_RESULT_INDV       = 38;


	btfDebit     = 0;
  btfCredit    = 1;

    { ERROR FIELD ID }
  EFI_CHNO                 = 1;
  EFI_BANKNO               = 2;
  EFI_ACCNO                = 3;
  EFI_TC                   = 4;
  EFI_AMOUNT               = 5;
  EFI_REF_NO               = 6;
  EFI_OP_NAME              = 7;
  EFI_CU_NAME              = 8;
  EFI_CU_RESIDENT          = 9;
  EFI_CU_CITIZEN           = 10;
  EFI_PROV_CODE            = 11;
  EFI_CITY_CODE            = 12;
  EFI_DOUBLE_RECORD				 = 13;
  EFI_REJECT_TSA					 = 14;
  EFI_CU_TYPE							 = 15;

implementation

end.
